### ISSUE TITLE
请问模型训练好之后怎么应用？

### ISSUE THREAD

**Issue by HickeyHsu** [Congyuwang/AlphaNetV3#11]
十分感谢分享！我用自己的数据训练了一个模型，请问怎么应用训练好的模型？（即测试集应用）
即：如何给模型输入测试集序列，输出return的label？

我尝试model.predict(test_data),其中test_data是一个TimeSeriesData，但似乎并不能成功。

`    # load entire model using load_model() from alphanet module
    model = load_model("model.bt")

    # only load weights by first creating a model instance
    model = AlphaNetV3(l2=0.001, dropout=0.0)
    model.load_weights("weights.bt")
    test_data=TimeSeriesData(
        dates=test_df["int_date"].values,                   # date column            
        data=test_df[metrics_std].values,                # data columns
        labels=test_df["future_return"].values # label column
    )
    output=model.predict(test_data.data)
    print(output)`

**Comment by Congyuwang** [comment]
您可以尝试将timeseries data传给trainval data, 设置train length为0（无训练长度），设置合适的val length。使用get获取tensorflow data，get的返回值可以用于predict

**Comment by Congyuwang** [comment]
或者你也可以尝试自己传递numpy.array给predict函数。
