### ISSUE TITLE
这个是涨跌准确率的意思，仅供参考。P(预测涨跌正确)

### ISSUE THREAD

**Issue by lorry3** [Congyuwang/AlphaNetV3#20]
这个是涨跌准确率的意思，仅供参考。P(预测涨跌正确)

_Originally posted by @Congyuwang in https://github.com/Congyuwang/AlphaNetV3/issues/18#issuecomment-999568854_
意思是，只要prediction与label同号（即同涨同跌）即可算作预测正确吗？不知道理解得对不对。

谢谢解答！

**Comment by Congyuwang** [comment]
正确

**Comment by lorry3** [comment]
谢谢🙏
