### ISSUE TITLE
Hello blogger, I would like to ask if you can provide the requirements.txt file? 

### ISSUE THREAD

**Issue by leofionn** [Congyuwang/AlphaNetV3#4]
Hello blogger, I would like to ask if you can provide the requirements.txt file? Or tell me the version of keras or tensorflow?
Because the APIs of different versions of tensorflow are particularly confusing, I want to use your code to reproduce the content in the series of Huatai Financial Engineering articles. Thank you again for your contribution!

**Comment by Congyuwang** [comment]
requirements.txt is not provided because tensorflow has a cpu and a gpu version. Use tensorflow-gpu >= 2.3 to <= 2.5 would be fine.
