### ISSUE TITLE
The Link of 'some_data.csv'

### ISSUE THREAD

**Issue by helonin** [Congyuwang/AlphaNetV3#5]
请问范例数据‘some_data.csv’能不能上传至云盘以供下载，谢谢！

**Comment by Congyuwang** [comment]
Please have a look at the documentation. https://github.com/Congyuwang/AlphaNetV3/blob/master/docs/alphanet.data.md#module-alphanetdata

**Comment by helonin** [comment]
The download didn't provided in the documentation. Help!

> 

- 

-
